<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\app\libs\Tinkwell.Cli.Sdk\Tinkwell.Cli.Sdk.csproj" />
    <ProjectReference Include="..\..\..\..\..\app\libs\Tinkwell.Coap\Tinkwell.Coap.csproj" />
    <ProjectReference Include="..\..\..\..\..\app\libs\Tinkwell.Package\Tinkwell.Package.csproj" />
    <ProjectReference Include="..\..\..\registry\src\Tinkwell.Firmlets.Registry.Client\Tinkwell.Firmlets.Registry.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\proto\firmwareless_proxy.proto" GrpcServices="Client" Link="Proto\firmwareless_proxy.proto" />
    <Protobuf Include="..\..\proto\firmwareless_assets.proto" GrpcServices="Client" Link="Proto\firmwareless_assets.proto" />
    <Protobuf Include="..\..\..\device\tw-device-sdk\proto\tw_protocol.proto" GrpcServices="None" Link="Proto\tw_protocol.proto" />
  </ItemGroup>

</Project>
